name: "dblinter"
description: "Launch a PG database, execute initial script and launch dblinter"
inputs:
  flyway-migration:
    description: "Flyway migration script"
    required: false
    default: ""
  init-script:
    description: "path where an initial script is."
    required: false
    default: ""

  report-path:
    description: "Path to write the sarif report file"
    required: true
    default: "dblinter.sarif"

  config-file:
    description: "Path to the dblinter config file if you want to use a custom one"
    required: false
    default: ""

  dblinter-version:
    description: "dblinter version"
    required: false
    default: "latest"

  postgres-version:
    description: "postgres version to use"
    required: false
    default: "17"
  flyway-version:
    description: "flyway version to use"
    required: false
    default: "10"

  pr-comment:
    description: "Display the report in the PR"
    required: false
    default: "false"
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github) to create the PR comment'
    default: ${{ github.token }}
    required: false

  exclude:
    description: "List of tables to exclude from the analysis"
    required: false
    default: ""

outputs:
  sarif-report:
    description: "sarif where the report is stored"

runs:
  using: "node20"
  main: "dist/index.js"
